### ISSUE TITLE
Installation and file locations

### ISSUE THREAD

**Issue by StotfoldSteve** [usermicrodevices/pybass#1]
I have previously used BASS with VB6 and was pleased to find the python implementation.

My first programs give the error

pygame 2.1.2 (SDL 2.0.18, Python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/Users/Steve/AppData/Local/Programs/Python/Python38/sjb_mp3c.py", line 8, in <module>
    from pybass.py import *
  File "C:/Users/Steve/AppData/Local/Programs/Python/Python38\pybass.py", line 62, in <module>
    bass_module = ctypes.WinDLL('bass')
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

I suspect that this is because of dotPY files and the BASS.DLL not being copied into the correct folder.
I would be grateful if you could advise please.

Thankyou for the library and I hope to resolve this issue. Best regards, Steve

**Comment by usermicrodevices** [comment]
`OSError: [WinError 193] %1 is not a valid Win32 application` - it's not pybass message. see your DLL file, perhaps between 32 or 64 valid selection

**Comment by StotfoldSteve** [comment]
I'm running Win10 so suspect I need the 64bit DLL. Which folder do I need to put it in? I've tried a few but without success. Thanks

**Comment by usermicrodevices** [comment]
`%1 is not a valid Win32 application` perhaps this message from Python 32 bit version. Check your Python compatibility with OS. BASS DLL must be located as current run directory or any [Python paths is accessible](https://docs.python.org/3/tutorial/modules.html#the-module-search-path)
